# Generated by Django 4.1.2 on 2022-11-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientes',
            old_name='ingrediente',
            new_name='nombre',
        ),
    ]
