# Generated by Django 4.1.2 on 2022-11-14 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_ingrediente_ingredientes_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredientes',
            new_name='Ingrediente',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='receta',
            name='cantidades',
        ),
    ]
